apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      serviceAccountName: filebeat
      # filebeat has to run as root to read logs, since the logs
      # on the host system are all owned by root. this is a little
      # scary, but at least all the host mounts are read-only, to minimize
      # possible damage.
      securityContext:
        runAsUser: 0
      # Tolerate all taints; run on every node
      tolerations:
        - operator: "Exists"
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.2
        # override the configuration path. because kubernetes can only mount directories
        # and not individual files
        command: [ "/usr/share/filebeat/filebeat"]
        args: [ "-e", "-path.config", "/usr/share/filebeat/config"]
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
        env:
          - name: LOGSTASH_HOSTS
            value: logstash-local:5044
          - name: LOG_LEVEL
            value: info
          - name: FILEBEAT_HOST
            valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/filebeat/config
        - name: filebeat-inputs
          mountPath: /usr/share/filebeat/inputs
        - name: varlog
          mountPath: /var/log/hostlogs
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: vartmp
          mountPath: /var/tmp/filebeat
      terminationGracePeriodSeconds: 30
      volumes:
      # mount the configmap with the filebeat config file
      - name: config-volume
        configMap:
          name: filebeat-configmap
          items:
            - key: filebeat.yml
              path: filebeat.yml
      - name: filebeat-inputs
        configMap:
          name: filebeat-inputs # inputs(prospectors) which define which logs to parse and send
      - name: varlog
        hostPath:
          path: /var/log # so system level logs (like kube-apiserver and etcd) can be read
      - name: vartmp
        hostPath:
          path: /var/tmp # persistent place to store the filebeat registry
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers # get friendly named symlinks to actual logs
      - name: varlogpods
        hostPath:
          path: /var/log/pods # where pod logs are collected
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers # where the logs _actually_ are
