{{- if not .Values.filebeatVersionGte6 }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
    {{- include "release_labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        app: filebeat
        {{- include "release_labels" . | indent 8 }}
      name: filebeat
      annotations:
        # Force DaemonSet to restart when configs change
        "checksum/filebeat-config": {{ include (print $.Template.BasePath "/configmap-filebeat.yaml") . | sha256sum }}
        "checksum/prospectors-config": {{ include (print $.Template.BasePath "/configmap-prospectors.yaml") . | sha256sum }}
    spec:
      containers:
      - name: filebeat
        image: "{{ .Values.image }}"
        command: ["filebeat", "-e", "-c", "conf/filebeat.yml"]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /usr/share/filebeat/conf
          name: filebeat-conf
        - mountPath: /usr/share/filebeat/prospectors
          name: filebeat-prospectors
        - mountPath: /usr/share/filebeat/ssl
          name: filebeat-ssl
        - mountPath: /usr/share/filebeat/data
          name: filebeat-data
        - name: varlog
          mountPath: /var/log/containers
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      tolerations:
        - operator: "Exists"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-conf
        configMap:
          name: filebeat-conf
      - name: filebeat-prospectors
        configMap:
          name: filebeat-prospectors
      - name: filebeat-data
        hostPath:
          path: /opt/share/filebeat/data
          #path: /usr/share/filebeat/data
      - name: filebeat-ssl
        secret:
          secretName: filebeat-ssl
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- end }}
