apiVersion: v1
kind: Service
metadata:
  name: {{ template "es.fullname" . }}-discovery
  labels:
    app: {{ template "es.fullname" . }}
    component: {{ template "es.fullname" . }}
    role: master
spec:
  selector:
    component: {{ template "es.fullname" . }}
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
