kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: tiller-${NAMESPACE}
  namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
