apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller-${NAMESPACE}-storageclass-admin
subjects:
  - kind: ServiceAccount
    name: tiller-${NAMESPACE}
    namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageclass-admin
