apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: authentication_handler_service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication_handler_service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # scale up if usage is above
        # 60% of the requested CPU (100m)
        averageUtilization: 60
