apiVersion: v1
kind: Service
metadata:
  name: authentication_handler_service
spec:
  type: ClusterIP
  selector:
    app: service
  ports:
    - name: HTTP_PORT
      port: 9897
      protocol: TCP
      targetPort: http
    - port: 9896
      targetPort: grpc
      protocol: TCP
      name: GRPC_PORT
