apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-service
spec:
  revisionHistoryLimit: 5
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: test-service
      annotations:
        "prometheus.io/scrape": "true"
    spec:
      containers:
        - name: test-service
          image: "gcosta/node-test-service"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: LOG_LEVEL
              value: "*"
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
