package constants

const (
	EMPTY                     = ""
	DB_CONNECTION_ATTEMPT     = "DB_CONNECTION_ATTEMPT"
	COLLECTOR_ENDPOINT        = "http://localhost:14268/api/traces"
	SERVICE_NAME_DEFAULT      = "MERCHANT_SERVICE"
	CREATE_MERCHANT_ACCOUNT   = "CREATE_MERCHANT_ACCOUNT"
	UPDATE_MERCHANT_ACCOUNT   = "UPDATE_MERCHANT_ACCOUNT"
	DELETE_MERCHANT_ACCOUNT   = "DELETE_MERCHANT_ACCOUNT"
	GET_MERCHANT_ACCOUNT      = "GET_MERCHANT_ACCOUNT"
	GET_MERCHANT_ACCOUNTS     = "GET_MERCHANT_ACCOUNTS"
	STRIPE_ACCOUNT_ONBOARDING = "account_onboarding"
)
