package constants

const (
	DELETE_ACCOUNT = "DELETE_ACCOUNT"
	GET_ACCOUNT    = "GET_ACCOUNT"
	LOCK_ACCOUNT   = "LOCK_ACCOUNT"
	LOGIN_ACCOUNT  = "LOGIN_ACCOUNT"
	LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT"
	UNLOCK_ACCOUNT = "UNLOCK_ACCOUNT"
	UPDATE_ACCOUNT = "UPDATE_ACCOUNT"
	CREATE_ACCOUNT = "CREATE_ACCOUNT"
	FAILURE        = "FAILURE"
	SUCCESS        = "SUCCESS"
)
