apiVersion: v1
kind: Service
metadata:
  name: authenticationservice
spec:
  type: ClusterIP
  selector:
    app: authenticationservice
  ports:
    - name: http
      port: 8404
      protocol: TCP
      targetPort: http
