#
# Deployment for NGINX Ingress controller.
# This is for routing Internal requests from private network
# Based on https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/default/rc-default.yaml
#
# VERY IMPORTANT: When is doubt, reload:
#   https://kubernetes.github.io/ingress-nginx/how-it-works/#when-a-reload-is-required
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ic-internal
  labels:
    app: nginx-ic-internal
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-ic-internal
        name: nginx-ic-internal
    spec:
      serviceAccountName: nginx-ic
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.8
        name: nginx-ic-internal
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 5
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - name: http
            containerPort: 80
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/ingress-controller-nginx-conf-elk-internal
        - --ingress-class=elk-internal-ingress
        # - --v=2 # logging level
