version: '3.7'

services:
  linkerd:
    image: buoyantio/linkerd:1.4.6
    container_name: linkerd
    ports:
      - "4142:4142"
      - "4141:4141"
      - "9990:9990"
    volumes:
      - "./config:/io.buoyant/linkerd/config:ro"
    command:
      - /io.buoyant/linkerd/config/linkerd.yml

  namerd:
    image: buoyantio/namerd:1.4.6
    container_name: namerd
    ports:
      - "4100:4100"
      - "4180:4180"
      - "9991:9991"
    volumes:
      - "./config:/io.buoyant/linkerd/config:ro"
    command:
      - /io.buoyant/linkerd/config/namerd.yml
