version: "3.7"

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER}
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    restart: unless-stopped
    networks:
      - monitor-net

  redis:
    container_name: ${REDIS_NAME}
    image: redis
    networks:
      - monitor-net
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}

  # docker run -it --rm  --publish 8080:3000   -e AUTHN_URL=http://localhost:8080   -e APP_DOMAINS=localhost   -e DATABASE_URL=sqlite3://:memory:?mode=memory\&cache=shared   -e SECRET_KEY_BASE=changeme   -e HTTP_AUTH_USERNAME=hello   -e HTTP_AUTH_PASSWORD=world   --name authn_app   keratin/authn-server:latest   sh -c "./authn migrate && ./authn server"
  service:
    container_name: ${SERVICE_NAME}
    image: keratin/authn-server:latest
    ports:
      - ${AUTHN_EXTERNAL_PORT}:${AUTHN_INTERNAL_PORT}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_EXTERNAL_PORT}/${POSTGRES_DB_NAME}?sslmode=disable
      AUTHN_URL: ${AUTHN_PRIVATE_BASE_URL}:${AUTHN_EXTERNAL_PORT}
      APP_DOMAINS: ${AUTHN_DOMAINS}
      SECRET_KEY_BASE: ${AUTHN_SECRET}
      REDIS_URL: ${REDIS_URL}
      HTTP_AUTH_USERNAME: ${AUTHN_USERNAME}
      HTTP_AUTH_PASSWORD: ${AUTHN_PASSWORD}
      ENABLE_SIGNUP: ${ENABLE_SIGNUP}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
      SESSION_KEY_SALT: ${SESSION_KEY_SALT}
      DB_ENCRYPTION_KEY_SALT: ${DB_ENCRYPTION_KEY_SALT}
      USERNAME_IS_EMAIL: ${USERNAME_IS_EMAIL}
      PASSWORD_POLICY_SCORE: ${PASSWORD_POLICY_SCORE}
      PASSWORD_CHANGE_LOGOUT: ${PASSWORD_CHANGE_LOGOUT}
      APP_PASSWORD_RESET_URL: ${APP_PASSWORD_RESET_URL}
      PASSWORD_RESET_TOKEN_TTL: ${PASSWORD_RESET_TOKEN_TTL}
      APP_PASSWORD_CHANGED_URL: ${APP_PASSWORD_CHANGED_URL}
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8405"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - monitor-net
    command: sh -c "./authn migrate && ./authn server"

networks:
  monitor-net:
    driver: bridge

volumes:
  postgres:
