name: Auth. Hdlr. Svc - E2E

on:
  push:
    branches:
      - '*'

jobs:
  kind-helm:
    strategy:
      matrix:
        helm-version:
          - 3.6.0
    env:
      working-directory: ./src/services/authentication_handler_service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          image: kindest/node:v1.19.11
      - name: Build container image
        working-directory: ${{env.working-directory}}
        run: |
          ./e2e_test/build.sh
          kind load docker-image test/service:latest
      - name: Setup Helm
        uses: ./.github/actions/helm
        with:
          helm-version: ${{ matrix.helm-version }}
      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: ./e2e_test/deploy.sh
      - name: Run integration tests
        working-directory: ${{env.working-directory}}
        run: ./e2e_test/test.sh
      - name: Debug failure
        if: failure()
        run: |
          kubectl logs -l app=service || true
