name: Auth. Hdlr. Svc - CVE-SCAN

on:
  push:
    branches:
      - '*'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        id: build
        working-directory: ./src/services/authentication_handler_service
        run: |
          IMAGE=test/service:${GITHUB_SHA}
          docker build -t ${IMAGE} .
          echo "::set-output name=image::$IMAGE"
      - name: Scan image
        uses: docker://docker.io/aquasec/trivy:latest
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 1 --severity MEDIUM,HIGH,CRITICAL ${{ steps.build.outputs.image }}
      - name: Publish helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: ./src/services/authentication_handler_service/charts
          target_dir: ./src/services/authentication_handler_service/charts
          commit_username: yoanyombapro1234
          commit_email: yoanyombapro@gmail.com
