on: push
name: Blackspace Core
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run common core library tests
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "./src/libraries/core"
          GO111MODULE: "on"
        with:
          args: make run-tests
      - name: setup test env. and run database tests
        working-directory: ./src/libraries/core/core-database
        run: make test
