{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  # name needs to be unique so that when used for different namespaces the
  # ServiceAccount subject doesn't get overwritted
  name: filebeat-monitor
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{- end }}
