{{- if .Values.curator.enabled }}
apiVersion: {{ .Values.curator.apiVersion }}
kind: CronJob
metadata:
  name: {{ template "es.fullname" . }}-curator
  labels:
    app: {{ template "es.fullname" . }}
spec:
  schedule: "{{ .Values.curator.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: "{{ .Values.image.curator.repository }}:{{ .Values.image.curator.tag }}"
            imagePullPolicy: {{ .Values.image.curator.pullPolicy }}
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {{ template "es.fullname" . }}-curator-config
          restartPolicy: OnFailure
{{- end }}
