apiVersion: v1
kind: Service
metadata:
  name: {{ template "es.fullname" . }}
  labels:
    app: {{ template "es.fullname" . }}
    component: {{ template "es.fullname" . }}
    role: data
spec:
  type: ClusterIP
  selector:
    component: {{ template "es.fullname" . }}
    role: data
  ports:
  - name: http-ingress
    port: {{ .Values.service.httpPort }}
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: {{ .Values.service.transportPort }}
    targetPort: 9300
    protocol: TCP
